import { GameFile } from "@/types/game";

export const seedGames: GameFile[] = [
  {
    id: "game-hot-takes",
    slug: "hot-takes",
    title: "Hot Takes",
    description:
      "Spicy debate prompts that will divide the room. Pick a side and defend it!",
    thumbnail_url: "/icons/hot-takes.svg",
    min_players: 3,
    max_players: 8,
    duration_minutes: 20,
    tags: ["debate", "party", "adults", "opinions"],
    price: 0,
    is_featured: true,
    timer_default_seconds: 0,
    randomizer_type: null,
    rules: `## How to Play Hot Takes

1. **Read the prompt** out loud to the group.
2. Everyone picks a side — **agree or disagree**.
3. Each side has **30 seconds** to make their case.
4. The group **votes** on who made the better argument.
5. The winning side gets **1 point** each.
6. Swipe for the next prompt!

**House Rules:** No fence-sitting allowed — you must pick a side!`,
    entries: [
      { id: "ht-1", primary: "Pineapple belongs on pizza", secondary: "It adds a sweet contrast that complements salty ham perfectly" },
      { id: "ht-2", primary: "It's acceptable to recline your seat on an airplane", secondary: "You paid for the seat, the recline feature exists for a reason" },
      { id: "ht-3", primary: "Breakfast for dinner is superior to dinner for breakfast", secondary: "Pancakes at 8pm hit different than steak at 7am" },
      { id: "ht-4", primary: "The toilet paper roll should go over, not under", secondary: "The original patent actually shows it going over" },
      { id: "ht-5", primary: "Hot dogs are sandwiches", secondary: "By structural definition: filling between bread = sandwich" },
      { id: "ht-6", primary: "It's okay to text 'K' as a full response", secondary: "Sometimes brevity is the soul of communication" },
      { id: "ht-7", primary: "Cereal is soup", secondary: "Liquid + solid ingredients in a bowl = soup by definition" },
      { id: "ht-8", primary: "The book is always better than the movie", secondary: "Books allow for deeper character development and imagination" },
      { id: "ht-9", primary: "You should shower in the morning, not at night", secondary: "Starting the day fresh vs. keeping your sheets clean" },
      { id: "ht-10", primary: "Cats are better pets than dogs", secondary: "Independent, clean, and don't need walks in the rain" },
      { id: "ht-11", primary: "It's fine to wear socks with sandals", secondary: "Comfort should always beat fashion rules" },
      { id: "ht-12", primary: "Social media has done more harm than good", secondary: "Connected billions but also increased anxiety and misinformation" },
      { id: "ht-13", primary: "GIF should be pronounced with a hard G", secondary: "It stands for Graphics — not Jraphics" },
      { id: "ht-14", primary: "Working from home is better than office work", secondary: "No commute, flexible schedule, pants optional" },
      { id: "ht-15", primary: "Tipping culture should be abolished", secondary: "Employers should pay fair wages instead" },
      { id: "ht-16", primary: "Die Hard is a Christmas movie", secondary: "It takes place at a Christmas party and has a redemption arc" },
      { id: "ht-17", primary: "You should eat the pizza crust", secondary: "It's basically free breadsticks" },
      { id: "ht-18", primary: "Monday is the worst day of the week", secondary: "Sunday evening dread is arguably worse" },
      { id: "ht-19", primary: "It's rude to show up exactly on time to a house party", secondary: "Fashionably late gives the host time to prepare" },
      { id: "ht-20", primary: "Sparkling water is just angry water", secondary: "The carbonation adds texture and sophistication" },
      { id: "ht-21", primary: "People who back into parking spots are showing off", secondary: "It's actually safer when leaving the spot" },
      { id: "ht-22", primary: "You should always split the bill equally", secondary: "Even if someone ordered way more — it's simpler" },
      { id: "ht-23", primary: "Summer is the most overrated season", secondary: "Too hot, too crowded, too many bugs" },
      { id: "ht-24", primary: "Alien life definitely exists somewhere", secondary: "The universe is too vast for us to be alone" },
      { id: "ht-25", primary: "It's weird to clap when the plane lands", secondary: "The pilot did their literal job" },
      { id: "ht-26", primary: "Chocolate ice cream is overrated", secondary: "Vanilla is the true king — more versatile, pairs with everything" },
      { id: "ht-27", primary: "You should never double-text someone", secondary: "Eagerness shouldn't be punished" },
      { id: "ht-28", primary: "Reality TV is a guilty pleasure everyone should admit to", secondary: "It's entertainment, not a character flaw" },
      { id: "ht-29", primary: "Cold pizza is better than reheated pizza", secondary: "The flavors meld overnight and the texture is perfect" },
      { id: "ht-30", primary: "Adulthood is just pretending you know what you're doing", secondary: "Nobody actually has it figured out" },
      { id: "ht-31", primary: "It's okay to ghost someone after one date", secondary: "You don't owe a stranger an explanation" },
      { id: "ht-32", primary: "Brunch is the greatest meal ever invented", secondary: "Day drinking + breakfast food = perfection" },
      { id: "ht-33", primary: "You should put your phone away at concerts", secondary: "Live in the moment instead of filming for Instagram" },
      { id: "ht-34", primary: "Board games are more fun than video games", secondary: "Face-to-face interaction can't be replicated digitally" },
      { id: "ht-35", primary: "People who use speakerphone in public should be fined", secondary: "Some people have hearing difficulties though" },
      { id: "ht-36", primary: "It's fine to talk to strangers in elevators", secondary: "A little human connection never hurt anyone" },
      { id: "ht-37", primary: "Breakfast is the most important meal of the day", secondary: "This was actually invented by a cereal company" },
      { id: "ht-38", primary: "You should always say yes to karaoke", secondary: "Nobody cares if you can sing — it's about the energy" },
      { id: "ht-39", primary: "Astrology is just personality fan fiction", secondary: "But it's fun and mostly harmless" },
      { id: "ht-40", primary: "The middle seat on a plane gets both armrests", secondary: "It's the unwritten rule of air travel" },
      { id: "ht-41", primary: "Ranch dressing goes with everything", secondary: "Pizza, wings, vegetables, fries — name something it doesn't work on" },
      { id: "ht-42", primary: "It's wrong to eat food at the grocery store before paying", secondary: "You're going to pay for it anyway" },
      { id: "ht-43", primary: "Naps are a sign of weakness", secondary: "Actually, many top performers swear by power naps" },
      { id: "ht-44", primary: "The Oxford comma is essential", secondary: "Without it: 'I love my parents, Batman and Wonder Woman'" },
      { id: "ht-45", primary: "Camping is just voluntarily being homeless", secondary: "Nature, stars, campfires — it's about the experience" },
      { id: "ht-46", primary: "You should never lend money to friends", secondary: "It always changes the dynamic of the relationship" },
      { id: "ht-47", primary: "Crocs are genuinely great shoes", secondary: "Comfortable, waterproof, and now fashion-forward" },
      { id: "ht-48", primary: "The best superpower would be time travel", secondary: "Flying, invisibility, and super strength are all better" },
      { id: "ht-49", primary: "It's okay to re-gift something you received", secondary: "Reduce waste, and the gift finds someone who appreciates it" },
      { id: "ht-50", primary: "New Year's Eve is the most overrated holiday", secondary: "Overpriced, overhyped, and always a letdown" },
      { id: "ht-51", primary: "You should always tell someone if they have food in their teeth", secondary: "A moment of embarrassment beats hours of oblivion" },
      { id: "ht-52", primary: "Robots will eventually take all our jobs", secondary: "They'll create new jobs we can't even imagine yet" },
    ],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "game-speed-sketch",
    slug: "speed-sketch",
    title: "Speed Sketch",
    description:
      "Draw fast, guess faster! Race against the clock to sketch prompts for your team.",
    thumbnail_url: "/icons/speed-sketch.svg",
    min_players: 3,
    max_players: 10,
    duration_minutes: 30,
    tags: ["drawing", "team", "fast-paced", "creative"],
    price: 0,
    is_featured: true,
    timer_default_seconds: 60,
    randomizer_type: "dice",
    randomizer_config: { sides: 6 },
    rules: `## How to Play Speed Sketch

1. Split into **two teams**.
2. One player from the active team is the **Sketcher**.
3. The Sketcher sees the prompt — **no talking, no letters, no numbers!**
4. Start the **60-second timer** and sketch!
5. Your team shouts guesses. If they get it, score a point!
6. If time runs out, the other team gets **one guess** to steal.
7. Alternate teams. First to **10 points** wins!

**Pro tip:** Use the dice randomizer to decide who sketches first!`,
    entries: [
      { id: "ss-1", primary: "Astronaut", secondary: "Space", category: "People" },
      { id: "ss-2", primary: "Spaghetti", secondary: "Food", category: "Food & Drink" },
      { id: "ss-3", primary: "Treehouse", secondary: "Buildings", category: "Places" },
      { id: "ss-4", primary: "Surfing", secondary: "Sports", category: "Activities" },
      { id: "ss-5", primary: "Volcano", secondary: "Nature", category: "Nature" },
      { id: "ss-6", primary: "DJ", secondary: "Music", category: "People" },
      { id: "ss-7", primary: "Roller coaster", secondary: "Amusement park", category: "Places" },
      { id: "ss-8", primary: "Snowman", secondary: "Winter", category: "Seasonal" },
      { id: "ss-9", primary: "Mermaid", secondary: "Fantasy", category: "Mythology" },
      { id: "ss-10", primary: "Hamburger", secondary: "Fast food", category: "Food & Drink" },
      { id: "ss-11", primary: "Parachute", secondary: "Skydiving", category: "Activities" },
      { id: "ss-12", primary: "Lighthouse", secondary: "Coastal", category: "Places" },
      { id: "ss-13", primary: "Unicorn", secondary: "Fantasy", category: "Mythology" },
      { id: "ss-14", primary: "Popcorn", secondary: "Snacks", category: "Food & Drink" },
      { id: "ss-15", primary: "Firefighter", secondary: "Emergency", category: "People" },
      { id: "ss-16", primary: "Igloo", secondary: "Arctic", category: "Places" },
      { id: "ss-17", primary: "Skateboard", secondary: "Sports", category: "Activities" },
      { id: "ss-18", primary: "Cactus", secondary: "Desert", category: "Nature" },
      { id: "ss-19", primary: "Pirate ship", secondary: "Adventure", category: "Vehicles" },
      { id: "ss-20", primary: "Wedding cake", secondary: "Celebration", category: "Food & Drink" },
      { id: "ss-21", primary: "Tornado", secondary: "Weather", category: "Nature" },
      { id: "ss-22", primary: "Robot", secondary: "Technology", category: "Sci-Fi" },
      { id: "ss-23", primary: "Penguin", secondary: "Animals", category: "Animals" },
      { id: "ss-24", primary: "Guitar", secondary: "Instruments", category: "Music" },
      { id: "ss-25", primary: "Waterfall", secondary: "Nature", category: "Nature" },
      { id: "ss-26", primary: "Ninja", secondary: "Martial arts", category: "People" },
      { id: "ss-27", primary: "Hot air balloon", secondary: "Flying", category: "Vehicles" },
      { id: "ss-28", primary: "Dragon", secondary: "Fantasy", category: "Mythology" },
      { id: "ss-29", primary: "Ice cream sundae", secondary: "Desserts", category: "Food & Drink" },
      { id: "ss-30", primary: "Scuba diving", secondary: "Ocean", category: "Activities" },
      { id: "ss-31", primary: "Haunted house", secondary: "Spooky", category: "Places" },
      { id: "ss-32", primary: "Elephant", secondary: "Animals", category: "Animals" },
      { id: "ss-33", primary: "Helicopter", secondary: "Aircraft", category: "Vehicles" },
      { id: "ss-34", primary: "Birthday party", secondary: "Celebration", category: "Events" },
      { id: "ss-35", primary: "Cowboy", secondary: "Western", category: "People" },
      { id: "ss-36", primary: "Palm tree", secondary: "Tropical", category: "Nature" },
      { id: "ss-37", primary: "Treasure chest", secondary: "Pirates", category: "Objects" },
      { id: "ss-38", primary: "Breakfast in bed", secondary: "Morning", category: "Activities" },
      { id: "ss-39", primary: "Butterfly", secondary: "Insects", category: "Animals" },
      { id: "ss-40", primary: "Castle", secondary: "Medieval", category: "Places" },
      { id: "ss-41", primary: "Sushi", secondary: "Japanese food", category: "Food & Drink" },
      { id: "ss-42", primary: "Mountain climbing", secondary: "Adventure", category: "Activities" },
      { id: "ss-43", primary: "Submarine", secondary: "Underwater", category: "Vehicles" },
      { id: "ss-44", primary: "Giraffe", secondary: "Animals", category: "Animals" },
      { id: "ss-45", primary: "Camping tent", secondary: "Outdoors", category: "Objects" },
      { id: "ss-46", primary: "Ballerina", secondary: "Dance", category: "People" },
      { id: "ss-47", primary: "Thunderstorm", secondary: "Weather", category: "Nature" },
      { id: "ss-48", primary: "Tacos", secondary: "Mexican food", category: "Food & Drink" },
      { id: "ss-49", primary: "Wizard", secondary: "Magic", category: "Mythology" },
      { id: "ss-50", primary: "Skiing", secondary: "Winter sports", category: "Activities" },
      { id: "ss-51", primary: "Octopus", secondary: "Sea creature", category: "Animals" },
      { id: "ss-52", primary: "Spaceship", secondary: "Sci-fi", category: "Vehicles" },
      { id: "ss-53", primary: "Ferris wheel", secondary: "Carnival", category: "Places" },
    ],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "game-two-truths",
    slug: "two-truths",
    title: "Two Truths & a Lie",
    description:
      "Share two truths and one lie about yourself. Can your friends spot the fib?",
    thumbnail_url: "/icons/two-truths.svg",
    min_players: 2,
    max_players: 20,
    duration_minutes: 15,
    tags: ["icebreaker", "social", "getting-to-know-you", "party"],
    price: 0,
    is_featured: false,
    timer_default_seconds: 0,
    randomizer_type: null,
    rules: `## How to Play Two Truths & a Lie

1. Each card shows a **theme or category**.
2. The active player thinks of **two true things** and **one lie** about themselves related to that theme.
3. Share all three statements with the group.
4. Everyone else **guesses which one is the lie**!
5. Score **1 point** for each person you fool.
6. Guessers score **1 point** for spotting the lie.
7. Swipe for the next theme!

**Tips:** The best lies are specific and believable. Mix mundane truths with an outrageous one!`,
    entries: [
      { id: "tt-1", primary: "Travel Adventures" },
      { id: "tt-2", primary: "Childhood Memories" },
      { id: "tt-3", primary: "Food & Eating Habits" },
      { id: "tt-4", primary: "Hidden Talents" },
      { id: "tt-5", primary: "Embarrassing Moments" },
      { id: "tt-6", primary: "Celebrity Encounters" },
      { id: "tt-7", primary: "School Days" },
      { id: "tt-8", primary: "Fears & Phobias" },
      { id: "tt-9", primary: "Jobs You've Had" },
      { id: "tt-10", primary: "Sports & Athletics" },
      { id: "tt-11", primary: "Music & Concerts" },
      { id: "tt-12", primary: "Family Stories" },
      { id: "tt-13", primary: "Late Night Adventures" },
      { id: "tt-14", primary: "Things You've Broken" },
      { id: "tt-15", primary: "Pets & Animals" },
      { id: "tt-16", primary: "Your Biggest Accomplishment" },
      { id: "tt-17", primary: "Movies & TV Shows" },
      { id: "tt-18", primary: "Cooking Disasters" },
      { id: "tt-19", primary: "Things You Collect" },
      { id: "tt-20", primary: "First Date Stories" },
      { id: "tt-21", primary: "Your Worst Habit" },
      { id: "tt-22", primary: "Dream Vacations" },
      { id: "tt-23", primary: "Things You've Won" },
      { id: "tt-24", primary: "Unusual Skills" },
      { id: "tt-25", primary: "Books That Changed You" },
      { id: "tt-26", primary: "Your Morning Routine" },
      { id: "tt-27", primary: "Technology Fails" },
      { id: "tt-28", primary: "Fashion Choices" },
      { id: "tt-29", primary: "Superstitions You Have" },
      { id: "tt-30", primary: "Things You've Built" },
      { id: "tt-31", primary: "Languages & Communication" },
      { id: "tt-32", primary: "Your Bucket List" },
      { id: "tt-33", primary: "Holidays & Traditions" },
      { id: "tt-34", primary: "Hobbies Past & Present" },
      { id: "tt-35", primary: "Your Hometown" },
      { id: "tt-36", primary: "Roommate Stories" },
      { id: "tt-37", primary: "Things That Scare You" },
      { id: "tt-38", primary: "Favorite Childhood Toy" },
      { id: "tt-39", primary: "Road Trip Tales" },
      { id: "tt-40", primary: "Your Secret Obsession" },
      { id: "tt-41", primary: "Dance Moves" },
      { id: "tt-42", primary: "Things You've Lost" },
      { id: "tt-43", primary: "Your Weirdest Purchase" },
      { id: "tt-44", primary: "Outdoor Adventures" },
      { id: "tt-45", primary: "Things You Do When Nobody's Watching" },
      { id: "tt-46", primary: "Your Guilty Pleasure" },
      { id: "tt-47", primary: "Nicknames You've Had" },
      { id: "tt-48", primary: "Life-Changing Moments" },
      { id: "tt-49", primary: "Your Biggest Fear" },
      { id: "tt-50", primary: "Something You've Never Told Anyone" },
      { id: "tt-51", primary: "Your Proudest Moment" },
      { id: "tt-52", primary: "The Strangest Thing You've Eaten" },
    ],
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];
